version: '3'

services:
  php-fpm:
    build:
      context: ./php-fpm
    volumes:
      - ../mindgeek:/var/www

  nginx:
    build:
      context: ./nginx
    volumes:
      - ../mindgeek:/var/www
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/sites/:/etc/nginx/sites-available
      - ./nginx/conf.d/:/etc/nginx/conf.d
      - ./logs:/var/log
    depends_on:
      - php-fpm
    ports:
      - "80:80"